{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Experimenting with data - syncing data to JanusGraph benchmarks - no debug"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "This notebook is a setup for experiments with JanusGraph.\n",
    "\n",
    " * [Graphexp](https://url.corp.redhat.com/thoth-sbu-graphexp-test1) - visualization of data available in JanusGraph\n",
    " * [Online documentation of Thoth](https://fridex.github.io/thoth/)\n",
    " * [Gremlin graph guide](http://kelvinlawrence.net/book/Gremlin-Graph-Guide.html)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from thoth.storages.graph import GraphDatabase\n",
    "from thoth.storages import SolverResultsStore\n",
    "from thoth.storages import AnalysisResultsStore\n",
    "\n",
    "from thoth.lab import obtain_location\n",
    "from thoth.lab import GraphQueryResult as gqr\n",
    "\n",
    "#graph_db = GraphDatabase.create(obtain_location('thoth-sbu-janusgraph-test1', verify=False, only_netloc=True), port=80)\n",
    "graph_db = GraphDatabase.create('localhost', port=8182)\n",
    "solver_results = SolverResultsStore('thoth-sbu', host=obtain_location('thoth-upshift-ceph', verify=False))\n",
    "analysis_results = AnalysisResultsStore('thoth-sbu', host=obtain_location('thoth-upshift-ceph', verify=False))\n",
    "\n",
    "graph_db.connect()\n",
    "solver_results.connect()\n",
    "analysis_results.connect()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Place for experiments:"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "These are benchmarks when running JanusGraph on a local machine. **Note** the debug mode of JanusGraph was turned **off**."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from thoth.common import init_logging\n",
    "\n",
    "# Let's keep info about enabling/disabling caches.\n",
    "init_logging({'thoth.storages.graph.utils': 'DEBUG'})"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Syncing image analysis results - without adapter cache"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "from thoth.lab import GraphQueryResult as gqr\n",
    "\n",
    "# Erase content of the graph database:\n",
    "gqr(graph_db.g.V().drop().next()).result\n",
    "assert gqr(graph_db.g.V().count().next()).result == 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "#list(analysis_results.get_document_listing())\n",
    "analysis_document = analysis_results.retrieve_document('fridex-thoth-package-extract-dash-4f47l')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEBUG:thoth.storages.graph.utils:Disabling edge graph cache\n",
      "DEBUG:thoth.storages.graph.utils:Disabling vertex graph cache\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "env: THOTH_STORAGES_DISABLE_CACHE=1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '3a040220698576d1854e38dc4b3dba5cbae5ad37'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/compat/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/compat/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '9776279006a6f04e9598f7d49f08a03ecfbc25e9'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/core/setup.py'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'result'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '366fdd5e9f97f920e292f8310ded16d5157a41ff'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/distutils/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/distutils/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '4687921b80b3754d404c5f5d21ef7d41f309cab8'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/f2py/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/f2py/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'bc13e5086c8278209634f14c1747d70611827b15'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/fft/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/fft/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '02119470e9cd3bf50e6cb76021619342ec985031'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/lib/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/lib/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '9225a83ce85be4ebcb68db14afdf32c46079d4e0'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/linalg/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/linalg/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'e4562b8b302e1998529dd582767363dd961c7987'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/ma/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/ma/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '182848d986caf013be63a6d1e546f3dd6a117fe3'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/matrixlib/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/matrixlib/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '80e1bb9ec02b2665a22381a3ad2608214c9dd923'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/polynomial/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/polynomial/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'ae1f99cb8e4db2637f3e7a6f005fc1e4d26938f4'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/random/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/random/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'd8c348d3295b598533beaee4c02708bd997cc8ae'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '5eacb723093dc6b1167569ed3d0c1e07d80068d9'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/testing/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/testing/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '04ec62f06a556ebb1002efabddf91e1afb23a667'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/_lib/setup.py'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'result'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'ce918a00590fb744bff6748548a976ed385beeec'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/cluster/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/cluster/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'a9cdb32174db46e06cbf026e12053ec0fd603636'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/constants/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/constants/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '827862f2272a8a45b0cf7cce2bcb3982e39c0262'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/fftpack/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/fftpack/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'a794ac17cc43b567d6528e2eaca1ee37e535e6d8'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/integrate/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/integrate/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'ed61f87e14fc94fddec16b143deb39f56014945b'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/interpolate/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/interpolate/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '107a91a9af82f00f7c111f08df67a88b47c63685'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/io/arff/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/io/arff/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'b6c60dd5f97f2316427a26f079c575dd06b3da06'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/io/harwell_boeing/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/io/harwell_boeing/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'fc6e35268d223ea9b6ef4d2d0c037b15d6e1f196'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/io/matlab/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/io/matlab/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '86a783eb77fe8fbd4d29866f90fbdff829c67189'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/io/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/io/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '0ab992e457ea8b2bf13a9092c93cb6a605b45c84'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/linalg/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/linalg/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '623e298f96f545a4ae9f43d9bf5c2ce6f64de4d1'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/misc/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/misc/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'd8493415bbea568f276aab3c8b69910bfac401f2'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/ndimage/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/ndimage/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '8a5316ce6f9692828a33996d742a0a065c18f149'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/odr/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/odr/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'dd7fdfee19ac277c54809ce8a42a8123c21e1333'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/optimize/_lsq/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/optimize/_lsq/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '272254aa57994c23a7369d18a1b364f7cff6fabf'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/optimize/_trlib/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/optimize/_trlib/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '69d8d567153ec00136c7aae70319d5f6ed7c265e'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/optimize/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/optimize/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'c6468cfa6119d2fbfcf9b929222f982a6daebfed'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'b7bcf1cd54fb2cfb694b7ec14f63287e348441e7'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/signal/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/signal/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'b43c089d67f749593dcd00f5fff8df109ae638b1'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/csgraph/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/csgraph/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '41f4841b2d14e62dff6e08c3f22392577f76d65d'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/dsolve/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/dsolve/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '1ead70c2848f0b080e150dedd78ccfb586e47433'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/arpack/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/arpack/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'abc654d8522d81b3893b220148579247d3a988e6'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/lobpcg/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/lobpcg/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '9b0e2c223ce8da2665d2894f3f485c5dc2750f45'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '9fe83c50c8dab8d50701e8621514de7970390d2f'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/isolve/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/isolve/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '0544d5895ad4c63377b84300d327bbd188bf202b'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '1178942fb494c4d4903566bccab1672ad8965acf'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'd1a2976f02b4fdc6bc4114ca9eb2b39939c081c7'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/spatial/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/spatial/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '356988e5c25ce2c755d30781afef4a9538dd45ee'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/special/_precompute/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/special/_precompute/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '5ee13ffef8d96e3e8e2c75205901c47e5c85fa59'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/special/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/special/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '8794ccb894c0b385bdade64548e4a551fa9f6e2a'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/stats/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/stats/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '1d41108c35ca9c92d145c556ba917db8f5082757'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/__check_build/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/__check_build/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '7dd8131f2ea9c8685248533cc473a1ebc5e0b2f4'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/cluster/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/cluster/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'b23cd2bee4a90d36fa18905661433467e005ae6a'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/datasets/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/datasets/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '5f3acc0e1821b891fd7e28b7de1c08c37fc49cf4'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/decomposition/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/decomposition/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '0b0761f33d17e3e8aae0661bdfc3fcd6b87e7463'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/ensemble/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/ensemble/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '8ae44a23e6f63fbb92f565a4259d62b038f0e7a3'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/externals/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/externals/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '81b04fb53de73bbdb490521b1c8c06bb8eeb5f8a'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/feature_extraction/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/feature_extraction/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'b92fab7baa233fab227b9ebbe99b1dec7462825c'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/linear_model/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/linear_model/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '9e30fe835a0eecdb3c64c7a794d0c290b01224e7'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/manifold/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/manifold/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'ead6ace4a319f3123f0d3905d2cf627e8628e8fe'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/metrics/cluster/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/metrics/cluster/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '59fe8fc3db33afac29ba1c5ea1ebd268fdb53dca'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/metrics/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/metrics/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'b6fe0f9ba3ff2189590c4828628e6486baef65e9'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/neighbors/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/neighbors/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'b2183d87a0f616fb13a0c50c5806cc51e2929d61'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '7ca0e496eb01411d2048e5ce73137dcb20e24324'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/svm/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/svm/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '5f8d9458e44f097b60e09456292f2bbd896a75f6'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/tree/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/tree/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'e47b1d5e9b1d2a2cd0554e848bce6441d2209360'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/utils/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/utils/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '1855857cc844a266cf9d8092d7fe038dad254b5b'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/utils/sparsetools/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/utils/sparsetools/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'a2aae58dbc144ace99c9ca9306619ceb07e0fe11'}, 'ecosystem': 'Python-RequirementsTXT', 'path': '/opt/app-root/share/doc/networkx-2.1/requirements.txt', 'result': {'dependencies': ['-r requirements/default.txt', '-r requirements/test.txt']}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 23.4 s, sys: 1.19 s, total: 24.6 s\n",
      "Wall time: 6min\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "%env THOTH_STORAGES_DISABLE_CACHE=1\n",
    "\n",
    "graph_db.sync_analysis_result(analysis_document)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of vertexes present in graph: 2827\n"
     ]
    }
   ],
   "source": [
    "print(f\"Number of vertexes present in graph: {gqr(graph_db.g.V().count().next()).result:d}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of edges present in graph: 9515\n"
     ]
    }
   ],
   "source": [
    "print(f\"Number of edges present in graph: {gqr(graph_db.g.E().count().next()).result:d}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Syncing image analysis results - with adapter cache"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "gqr(graph_db.g.V().drop().next())\n",
    "assert gqr(graph_db.g.V().count().next()).result == 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEBUG:thoth.storages.graph.utils:Enabling edge graph cache\n",
      "DEBUG:thoth.storages.graph.utils:Enabling vertex graph cache\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "env: THOTH_STORAGES_DISABLE_CACHE=0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '3a040220698576d1854e38dc4b3dba5cbae5ad37'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/compat/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/compat/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '9776279006a6f04e9598f7d49f08a03ecfbc25e9'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/core/setup.py'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'result'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '366fdd5e9f97f920e292f8310ded16d5157a41ff'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/distutils/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/distutils/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '4687921b80b3754d404c5f5d21ef7d41f309cab8'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/f2py/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/f2py/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'bc13e5086c8278209634f14c1747d70611827b15'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/fft/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/fft/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '02119470e9cd3bf50e6cb76021619342ec985031'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/lib/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/lib/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '9225a83ce85be4ebcb68db14afdf32c46079d4e0'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/linalg/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/linalg/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'e4562b8b302e1998529dd582767363dd961c7987'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/ma/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/ma/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '182848d986caf013be63a6d1e546f3dd6a117fe3'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/matrixlib/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/matrixlib/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '80e1bb9ec02b2665a22381a3ad2608214c9dd923'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/polynomial/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/polynomial/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'ae1f99cb8e4db2637f3e7a6f005fc1e4d26938f4'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/random/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/random/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'd8c348d3295b598533beaee4c02708bd997cc8ae'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '5eacb723093dc6b1167569ed3d0c1e07d80068d9'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/numpy/testing/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/numpy/testing/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '04ec62f06a556ebb1002efabddf91e1afb23a667'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/_lib/setup.py'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'result'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'ce918a00590fb744bff6748548a976ed385beeec'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/cluster/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/cluster/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'a9cdb32174db46e06cbf026e12053ec0fd603636'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/constants/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/constants/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '827862f2272a8a45b0cf7cce2bcb3982e39c0262'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/fftpack/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/fftpack/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'a794ac17cc43b567d6528e2eaca1ee37e535e6d8'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/integrate/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/integrate/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'ed61f87e14fc94fddec16b143deb39f56014945b'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/interpolate/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/interpolate/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '107a91a9af82f00f7c111f08df67a88b47c63685'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/io/arff/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/io/arff/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'b6c60dd5f97f2316427a26f079c575dd06b3da06'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/io/harwell_boeing/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/io/harwell_boeing/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'fc6e35268d223ea9b6ef4d2d0c037b15d6e1f196'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/io/matlab/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/io/matlab/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '86a783eb77fe8fbd4d29866f90fbdff829c67189'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/io/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/io/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '0ab992e457ea8b2bf13a9092c93cb6a605b45c84'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/linalg/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/linalg/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '623e298f96f545a4ae9f43d9bf5c2ce6f64de4d1'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/misc/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/misc/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'd8493415bbea568f276aab3c8b69910bfac401f2'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/ndimage/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/ndimage/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '8a5316ce6f9692828a33996d742a0a065c18f149'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/odr/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/odr/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'dd7fdfee19ac277c54809ce8a42a8123c21e1333'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/optimize/_lsq/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/optimize/_lsq/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '272254aa57994c23a7369d18a1b364f7cff6fabf'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/optimize/_trlib/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/optimize/_trlib/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '69d8d567153ec00136c7aae70319d5f6ed7c265e'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/optimize/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/optimize/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'c6468cfa6119d2fbfcf9b929222f982a6daebfed'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'b7bcf1cd54fb2cfb694b7ec14f63287e348441e7'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/signal/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/signal/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'b43c089d67f749593dcd00f5fff8df109ae638b1'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/csgraph/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/csgraph/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '41f4841b2d14e62dff6e08c3f22392577f76d65d'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/dsolve/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/dsolve/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '1ead70c2848f0b080e150dedd78ccfb586e47433'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/arpack/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/arpack/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'abc654d8522d81b3893b220148579247d3a988e6'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/lobpcg/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/lobpcg/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '9b0e2c223ce8da2665d2894f3f485c5dc2750f45'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '9fe83c50c8dab8d50701e8621514de7970390d2f'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/isolve/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/isolve/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '0544d5895ad4c63377b84300d327bbd188bf202b'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/linalg/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '1178942fb494c4d4903566bccab1672ad8965acf'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/sparse/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/sparse/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'd1a2976f02b4fdc6bc4114ca9eb2b39939c081c7'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/spatial/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/spatial/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '356988e5c25ce2c755d30781afef4a9538dd45ee'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/special/_precompute/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/special/_precompute/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '5ee13ffef8d96e3e8e2c75205901c47e5c85fa59'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/special/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/special/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '8794ccb894c0b385bdade64548e4a551fa9f6e2a'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/scipy/stats/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/scipy/stats/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '1d41108c35ca9c92d145c556ba917db8f5082757'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/__check_build/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/__check_build/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '7dd8131f2ea9c8685248533cc473a1ebc5e0b2f4'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/cluster/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/cluster/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'b23cd2bee4a90d36fa18905661433467e005ae6a'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/datasets/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/datasets/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '5f3acc0e1821b891fd7e28b7de1c08c37fc49cf4'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/decomposition/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/decomposition/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '0b0761f33d17e3e8aae0661bdfc3fcd6b87e7463'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/ensemble/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/ensemble/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '8ae44a23e6f63fbb92f565a4259d62b038f0e7a3'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/externals/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/externals/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '81b04fb53de73bbdb490521b1c8c06bb8eeb5f8a'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/feature_extraction/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/feature_extraction/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'b92fab7baa233fab227b9ebbe99b1dec7462825c'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/linear_model/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/linear_model/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '9e30fe835a0eecdb3c64c7a794d0c290b01224e7'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/manifold/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/manifold/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'ead6ace4a319f3123f0d3905d2cf627e8628e8fe'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/metrics/cluster/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/metrics/cluster/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '59fe8fc3db33afac29ba1c5ea1ebd268fdb53dca'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/metrics/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/metrics/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'b6fe0f9ba3ff2189590c4828628e6486baef65e9'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/neighbors/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/neighbors/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'b2183d87a0f616fb13a0c50c5806cc51e2929d61'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '7ca0e496eb01411d2048e5ce73137dcb20e24324'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/svm/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/svm/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '5f8d9458e44f097b60e09456292f2bbd896a75f6'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/tree/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/tree/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'e47b1d5e9b1d2a2cd0554e848bce6441d2209360'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/utils/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/utils/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': '1855857cc844a266cf9d8092d7fe038dad254b5b'}, 'ecosystem': 'Python', 'path': '/opt/app-root/lib/python3.6/site-packages/sklearn/utils/sparsetools/setup.py', 'result': {'error': 'no calls to setup found for: /tmp/tmp25bugu_h/rootfs/opt/app-root/lib/python3.6/site-packages/sklearn/utils/sparsetools/setup.py'}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n",
      "ERROR:thoth.storages.graph.janusgraph:Failed to sync Python package, error is not fatal: {'digests': {'manifest': 'a2aae58dbc144ace99c9ca9306619ceb07e0fe11'}, 'ecosystem': 'Python-RequirementsTXT', 'path': '/opt/app-root/share/doc/networkx-2.1/requirements.txt', 'result': {'dependencies': ['-r requirements/default.txt', '-r requirements/test.txt']}}\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py\", line 212, in sync_analysis_result\n",
      "    python_package_version = PythonPackageVersion.construct(python_package_info)\n",
      "  File \"/home/fpokorny/.virtualenvs/thoth-notebooks-7XLP4Rya/lib/python3.6/site-packages/thoth/storages/graph/models.py\", line 68, in construct\n",
      "    name=package_info['result']['name'],\n",
      "KeyError: 'name'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 32.5 s, sys: 827 ms, total: 33.4 s\n",
      "Wall time: 2min 54s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "%env THOTH_STORAGES_DISABLE_CACHE=0\n",
    "\n",
    "graph_db.sync_analysis_result(analysis_document)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of vertexes present in graph: 2827\n"
     ]
    }
   ],
   "source": [
    "print(f\"Number of vertexes present in graph: {gqr(graph_db.g.V().count().next()).result:d}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of edges present in graph: 9515\n"
     ]
    }
   ],
   "source": [
    "print(f\"Number of edges present in graph: {gqr(graph_db.g.E().count().next()).result:d}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Syncing solver results - without adapter cache"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "gqr(graph_db.g.V().drop().next())\n",
    "assert gqr(graph_db.g.V().count().next()).result == 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "solver_document = solver_results.retrieve_document('fridex-thoth-solver-fc27-thoth-solver-fc27-92qtv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEBUG:thoth.storages.graph.utils:Disabling edge graph cache\n",
      "DEBUG:thoth.storages.graph.utils:Disabling vertex graph cache\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "env: THOTH_STORAGES_DISABLE_CACHE=1\n",
      "CPU times: user 41.7 s, sys: 2.08 s, total: 43.8 s\n",
      "Wall time: 10min 29s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "%env THOTH_STORAGES_DISABLE_CACHE=1\n",
    "\n",
    "graph_db.sync_solver_result(solver_document)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of vertexes present in graph: 653\n"
     ]
    }
   ],
   "source": [
    "print(f\"Number of vertexes present in graph: {gqr(graph_db.g.V().count().next()).result:d}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of edges present in graph: 9075\n"
     ]
    }
   ],
   "source": [
    "print(f\"Number of edges present in graph: {gqr(graph_db.g.E().count().next()).result:d}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Syncing solver results - with adapter cache"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "gqr(graph_db.g.V().drop().next())\n",
    "assert gqr(graph_db.g.V().count().next()).result == 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEBUG:thoth.storages.graph.utils:Enabling edge graph cache\n",
      "DEBUG:thoth.storages.graph.utils:Enabling vertex graph cache\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "env: THOTH_STORAGES_DISABLE_CACHE=0\n",
      "CPU times: user 27.5 s, sys: 799 ms, total: 28.3 s\n",
      "Wall time: 1min 26s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "%env THOTH_STORAGES_DISABLE_CACHE=0\n",
    "\n",
    "graph_db.sync_solver_result(solver_document)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of vertexes present in graph: 653\n"
     ]
    }
   ],
   "source": [
    "print(f\"Number of vertexes present in graph: {gqr(graph_db.g.V().count().next()).result:d}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of edges present in graph: 9075\n"
     ]
    }
   ],
   "source": [
    "print(f\"Number of edges present in graph: {gqr(graph_db.g.E().count().next()).result:d}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
